#!/usr/bin/env python3
import shell
import yaml
import json
import util.strings
import logging
import os
import argh
import cli_gcp


def main(*selectors,
         region=os.environ['GCP_REGION'],
         project=os.environ['GCP_PROJECT']):
    zones = shell.run('gcp-zones --region', region, echo=False).splitlines()
    for zone in zones:
        for instance in cli_gcp.ls(project, zone, selectors, 'running'):
            assert len(instance['networkInterfaces']) == 1, yaml.dump(instance)
            assert len(instance['networkInterfaces'][0]['accessConfigs']) == 1, yaml.dump(instance)
            print(instance['networkInterfaces'][0]['accessConfigs'][0]['natIP'])

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
