#!/usr/bin/env python3
import sys
import shell
import logging
import os
import argh
import cli_gcp

def main(*selectors,
         region=os.environ['GCP_REGION'],
         project=os.environ['GCP_PROJECT'],
         yes=False):
    assert selectors, 'you just tried to delete all things'
    state = 'running'
    zones = shell.run('gcp-zones --region', region).splitlines()
    logging.info('going to delete:\n')
    names = []
    for zone in zones:
        for instance in cli_gcp.ls(project, zone, selectors, state):
            names += [instance['name']]
            print(cli_gcp.format(instance))
    if not yes:
        logging.info('\nwould you like to proceed? y/n\n')
        assert shell.getch() == 'y', 'abort'
    failures = []
    for name in names:
        try:
            cli_gcp.compute().instances().delete(project=project, zone=zone, instance=name).execute()
        except:
            logging.info(f'failed to delete: {name}')
        logging.info(f'deleted: {name}')
    if failures:
        sys.exit(1)

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
