#!/usr/bin/env python3
import sys
import argh
import cli_gcp
import os
import shell
import yaml

def main(name=None,
         verbose=False,
         project=os.environ['GCP_PROJECT'],
         region=os.environ['GCP_REGION'],):
    lb_name = name
    zones = shell.run('gcp-zones --region', region, echo=False).splitlines()

    c = cli_gcp.compute()

    xs = [
        ('instance templates',        c.instanceTemplates(),     [{}]),
        ('backend services',          c.backendServices(),       [{}]),
        ('autoscalers',               c.autoscalers(),           [{'zone': zone} for zone in zones]),
        ('instance group managers',   c.instanceGroupManagers(), [{'zone': zone} for zone in zones]),
        ('health checks',             c.healthChecks(),          [{}]),
        ('ssl certs',                 c.sslCertificates(),       [{}]),
        ('global forwarding rules',   c.globalForwardingRules(), [{}]),
        ('target http proxies',       c.targetHttpProxies(),     [{}]),
        ('target https proxies',      c.targetHttpsProxies(),    [{}]),
        ('url maps',                  c.urlMaps(),               [{}]),
        ('firewall allows',           c.firewalls(),             [{}], lambda x: x['name'].endswith('-firewall-allow-health-checks')),
        ('global addresses',          c.globalAddresses(),       [{}]),
        # TODO this is how we can see healthy status of the pool
        # listManagedInstances(project=*, zone=*, instanceGroupManager=*, order_by=None, maxResults=None, pageToken=None, filter=None)
    ]

    addresses = []

    for x in xs:
        try:
            name, obj, kws = x
        except ValueError:
            name, obj, kws, filter = x

        res = []
        for kw in kws:
            req = obj.list(project=project, **kw)
            while req:
                resp = req.execute()
                for item in resp.get('items', []):
                    if not lb_name or item['name'].startswith(f'{lb_name}-'):
                        res.append(item)
                req = obj.list_next(req, resp)
        if verbose:
            print(yaml.dump({name: res}).strip())
        else:
            for r in res:
                print(r['name'])

        if name == 'global addresses':
            addresses = res

    # lookup dns A records via ipv4, since a records don't have names or labels
    if addresses: # can only lookup dns if addresses exists
        a_records = {}
        for zone in cli_gcp.dns_client().list_zones():
            for record in zone.list_resource_record_sets():
                a_records[record.rrdatas[0]] = (record, zone)
        for address in addresses:
            ipv4_address = address['address']
            if ipv4_address in a_records:
                record, zone = a_records[ipv4_address]
                name = address['name'].replace('-ip-address', '-dns-a-record')
                if verbose:
                    print(name, ipv4_address, record.name)
                else:
                    print(name)

    if not addresses:
        sys.exit(1)

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
