#!/usr/bin/env python3
import yaml
import shell
import logging
import googleapiclient.errors
import googleapiclient.discovery
import os
import argh
import cli_gcp
from util.retry import retry

def main(name,
         region=os.environ['GCP_REGION'],
         project=os.environ['GCP_PROJECT'],
         yes=False):
    zones = shell.run('gcp-zones --region', region, echo=False).splitlines()

    c = cli_gcp.compute()
    xs = [('firewall',              c.firewalls(),             {'project': project, 'firewall':         f'{name}-firewall-allow-health-checks'}),
          ('http forwarding rule',  c.globalForwardingRules(), {'project': project, 'forwardingRule':   f'{name}-http-forwarding-rules'}),
          ('https forwarding rule', c.globalForwardingRules(), {'project': project, 'forwardingRule':   f'{name}-https-forwarding-rules'}),
          ('http proxy',            c.targetHttpProxies(),     {'project': project, 'targetHttpProxy':  f'{name}-http-proxy'}),
          ('https proxy',           c.targetHttpsProxies(),    {'project': project, 'targetHttpsProxy': f'{name}-https-proxy'}),
          ('global address',        c.globalAddresses(),       {'project': project, 'address':          f'{name}-ip-address'}),
          ('ssl cert',              c.sslCertificates(),       {'project': project, 'sslCertificate':   f'{name}-ssl-cert'}),
          ('url map',               c.urlMaps(),               {'project': project, 'urlMap':           f'{name}-url-map'}),
          ('backend service',       c.backendServices(),       {'project': project, 'backendService':   f'{name}-backend-service'})]
    for zone in zones:
        xs += [('autoscalers',            c.autoscalers(),           {'project': project, 'autoscaler':             f'{name}-autoscaler', 'zone': zone}),
               ('instance group manager', c.instanceGroupManagers(), {'project': project, 'instanceGroupManager':   f'{name}-instance-group-manager', 'zone': zone}),
               ('instance group manager', c.instanceGroupManagers(), {'project': project, 'instanceGroupManager':   f'{name}-instance-group-manager', 'zone': zone})] # TODO why do we have to call delete twice for this?
    xs += [('instance template',        c.instanceTemplates(),  {'project': project, 'instanceTemplate': f'{name}-instance-template'}),
           ('health check',             c.healthChecks(),       {'project': project, 'healthCheck':      f'{name}-health-checks'})]

    if not yes:
        logging.info('going to delete:\n')
        for name, obj, kw in xs:
            logging.info(f'{name}:')
            try:
                res = obj.get(**kw).execute()
            except googleapiclient.errors.HttpError as e:
                if e.resp.status != 404:
                    raise
            else:
                logging.info(yaml.dump({name: res}))
        logging.info('\nwould you like to proceed? y/n\n')
        assert shell.getch() == 'y', 'abort'

    for name, obj, kw in xs:
        try:
            res = retry(obj.delete(**kw).execute, times=20, exponent=1.5, allowed_exception_fn=lambda e: e.resp.status == 404)() # can't be deleted before upstream components actually gone
        except googleapiclient.errors.HttpError as e:
            if e.resp.status != 404:
                raise
            logging.info(f'already deleted: {name}')
        else:
            logging.info(yaml.dump({name: res}))

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
