#!/usr/bin/env python3
import sys
import os
import argh
import cli_gcp

def main(project=os.environ['GCP_PROJECT']):
    req = cli_gcp.compute().firewalls().list(project=project)
    print('name', 'direction', 'source-ranges', 'target-tags', 'allows', 'denies', 'priority', file=sys.stderr)
    while req:
        resp = req.execute()
        for item in resp.get('items', []):
            if not item['disabled']:
                print(
                    item['name'],
                    item['direction'].lower(),
                    ','.join(item.get('sourceRanges', [])) or '-',
                    ','.join(item.get('targetTags', [])) or '-',
                    ','.join(f'{x["IPProtocol"]}:{";".join(x.get("ports", ""))}' for x in item.get('allowed', [])).rstrip(':') or '-',
                    ','.join(f'{x["IPProtocol"]}:{";".join(x.get("ports", ""))}' for x in item.get('denied', [])).rstrip(':') or '-',
                    item['priority'],
                )
        req = cli_gcp.compute().firewalls().list_next(req, resp)

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
