#!/usr/bin/env python3
import yaml
import shell
import json
import logging
import os
import argh
import cli_gcp

def main(name,
         project=os.environ['GCP_PROJECT'],
         region=os.environ['GCP_REGION'],
         zone=os.environ['GCP_ZONE'],
         timeout=30,
         port_name="http-port",
         balancing_mode='UTILIZATION',
         init='',
         port=8080,
         target_size=3,
         target_size_surge=10,
         health_check_http_path="/health"):

    instance_template_name = f'{name}-instance-template'
    if init:
        init = f'--init "{init}"'
    firewall_network_tag = f'{name}-allow-health-checks'
    instance_config = json.loads(shell.run('gcp-compute-new',
                                           f'{name}-instance',
                                           '--return-config-only',
                                           '--zone', zone,
                                           '--network-tag', firewall_network_tag,
                                           init))
    instance_config['machineType'] = instance_config['machineType'].split('/')[-1]
    for disk in instance_config['disks']:
        if 'diskType' in disk['initializeParams']:
            disk['initializeParams']['diskType'] = disk['initializeParams']['diskType'].split('/')[-1]
    instance_template = cli_gcp.ensure.instance_template(project, instance_template_name, instance_config)
    instance_template_url = instance_template.get('targetLink') or instance_template['selfLink'] # target if created, self if already exists
    logging.info(yaml.dump({'instanceTemplate': instance_template}))

    health_check_name = f'{name}-health-checks'
    health_check = cli_gcp.ensure.health_check(project, health_check_name, health_check_http_path, port)
    health_check_url = health_check.get('targetLink') or health_check['selfLink'] # target if created, self if already exists
    logging.info(yaml.dump({'healthCheck': health_check}))

    instance_group_manager_name = f'{name}-instance-group-manager'
    instance_group_manager = cli_gcp.ensure.managed_instance_group(project, zone, name, health_check_url, target_size, target_size_surge, instance_template_url, port_name, port, instance_group_manager_name)
    logging.info(yaml.dump({'instanceGroup': instance_group_manager}))

    backend_service_name = f'{name}-backend-service'
    backend_service = cli_gcp.ensure.backend_service(project, timeout, health_check_url, port_name, backend_service_name)
    backend_service_url = backend_service.get('targetLink') or backend_service['selfLink'] # target if created, self if already exists
    logging.info(yaml.dump({'backendService': backend_service}))

    cli_gcp.ensure.backend_has_instance_group(project, zone, backend_service_name, instance_group_manager_name, balancing_mode, health_check_url)

    url_map_name = f'{name}-url-map'
    url_map = cli_gcp.ensure.url_map(project, url_map_name, backend_service_url)
    url_map_url = url_map.get('targetLink') or url_map['selfLink'] # target if created, self if already exists

    ip_address_name = f'{name}-ip-address'
    ip_address = cli_gcp.ensure.global_ip_address(project, ip_address_name)

    ssl_cert_name = f'{name}-ssl-cert'
    ssl_cert = cli_gcp.ensure.ssl_cert(project, ssl_cert_name, ip_address['address'])
    ssl_cert_url = ssl_cert.get('targetLink') or ssl_cert['selfLink'] # target if created, self if already exists

    https_proxy_name = f'{name}-https-proxy'
    https_proxy = cli_gcp.ensure.https_proxy(project, https_proxy_name, url_map_url, ssl_cert_url)
    https_proxy_url = https_proxy.get('targetLink') or https_proxy['selfLink'] # target if created, self if already exists

    https_forwarding_rules_name = f'{name}-https-forwarding-rules'
    cli_gcp.ensure.global_forwarding_rules(project, https_forwarding_rules_name, https_proxy_url, ip_address['address'], '443-443')

    http_proxy_name = f'{name}-http-proxy'
    http_proxy = cli_gcp.ensure.http_proxy(project, http_proxy_name, url_map_url)
    http_proxy_url = http_proxy.get('targetLink') or http_proxy['selfLink'] # target if created, self if already exists

    http_forwarding_rules_name = f'{name}-http-forwarding-rules'
    cli_gcp.ensure.global_forwarding_rules(project, http_forwarding_rules_name, http_proxy_url, ip_address['address'], '80-80')

    firewall_rule_name = f'{name}-firewall-allow-health-checks'
    official_gcp_ips = ['35.191.0.0/16', '130.211.0.0/22']
    cli_gcp.ensure.firewall_allow(project, firewall_rule_name, official_gcp_ips, firewall_network_tag, port)

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
