#!/usr/bin/env python3
import shell
import os
import argh
import cli_gcp
import sys
from util.retry import retry

def main(name,
         zone=None,
         verbose=False,
         suffix='',
         project=os.environ['GCP_PROJECT']):
    assert zone, '--zone must be specified'
    assert suffix, 'you must specify --suffix'
    suffix = f'-{suffix}'
    group_name = f'{name}-instance-group-manager-{zone}{suffix}'
    backend_service_name = f'{name}-backend-service'
    cli_gcp.ensure.backend_hasnt_instance_group(verbose, project, zone, backend_service_name, group_name)


if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
