#!/usr/bin/env python3
import shell
import os
import argh
import cli_gcp
import datetime
import yaml

def main(name,
         *selectors,
         size_gb='10',
         region=os.environ['GCP_REGION'],
         project=os.environ['GCP_PROJECT']):
    assert selectors, 'you must provide some selectors'
    zones = shell.run('gcp-zones --region', region, echo=False).splitlines()
    instances = []
    for zone in zones:
        for instance in cli_gcp.ls(project, zone, selectors, 'terminated'):
            instances.append(instance)
    assert len(instances) == 1, f'you can only image a single image, not: {[i["name"] for i in instances]}'
    assert instances[0]['disks'][0]['boot']
    config = {"family": name,
              "sourceDisk": instances[0]['disks'][0]['source'],
              "name": name + '-' + datetime.datetime.utcnow().isoformat().split('.')[0].replace(':', '-').lower() + 'z'}
    res = cli_gcp.compute().images().insert(project=project, body=config).execute()
    print(yaml.dump(res))

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
