#!/usr/bin/env python3
import shell
import os
import argh
import cli_gcp
import logging

def main(ip=shell.run('curl --fail checkip.amazonaws.com') + '/32',
         project=os.environ['GCP_PROJECT']):
    logging.info(f'using ip: {ip}')
    shell.run(
        'gcp-compute-firewall-add',
        f'authorize-ssh-{ip.replace(".", "-").replace("/", "--")}',
        '-s', f'{ip}',
        '--port 22',
    )

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
