#!/usr/bin/env python3
import logging
import sys
import time
import shell
import argh
import cli_gcp

def main(name,
         suffix=None,
         timeout_seconds=60 * 5,
         zone=None):
    assert suffix, 'you must specify --suffix'
    assert zone, 'you must specify --zone'
    lb_name = name
    start = time.time()
    while True:
        if time.time() - start > timeout_seconds:
            logging.info('timeout')
            sys.exit(1)
        fail = False
        instances = shell.run('gcp-compute-lb-group-ls', lb_name, '--suffix', suffix, '--zone', zone, '--instances-only', echo=False).splitlines()
        for instance in instances:
            id, state, health = instance.split()
            if state != 'RUNNING':
                fail = True
                logging.info(f'waiting for {id} to be state=RUNNING, currently: {state}')
            elif health != 'HEALTHY':
                fail = True
                logging.info(f'waiting for {id} to be health=HEALTHY, currently: {health}')
        if not fail:
            return

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
