#!/usr/bin/env python3
import shell
import os
import argh
import cli_gcp

@argh.arg('-n', '--network-tag', action='append')
def main(name,
         project=os.environ['GCP_PROJECT'],
         priority=1000,
         source_range='0.0.0.0/0',
         network_tag=None,
         mode='allow',
         proto='tcp',
         port='8080',
         description='',
         direction='ingress'):
    network_tags = network_tag or []
    assert source_range.count('.') == 3 and source_range.count('/') == 1 and source_range.replace('.', '').replace('/', '').isdigit(), f'bad source range, should be like: 0.0.0.0/0, not: {source_range}'
    assert mode in {'allow', 'deny'}, f'bad mode, should be allow or deny, not: {mode}'
    assert direction in {'ingress', 'egress'}, f'bad direction, should be ingress or egress, not: {direction}'
    if mode == 'allow':
        fn = cli_gcp.ensure.firewall_allow
    elif mode == 'deny':
        fn = cli_gcp.ensure.firewall_deny
    fn(project, name, [source_range], network_tags, port, proto, direction, priority, description)

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
