#!/usr/bin/env python3
import argh
import cli_gcp
import os

def main(name,
         project=os.environ['GCP_PROJECT']):
    return cli_gcp.compute().globalAddresses().get(project=project, address=f'{name}-ip-address').execute()['address']

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
