#!/usr/bin/env python3
import os
import argh
import cli_gcp
from util.retry import retry

def main(name,
         zone=None,
         verbose=False,
         suffix='',
         balancing_mode='UTILIZATION',
         project=os.environ['GCP_PROJECT']):
    assert suffix, 'you must specify --suffix'
    lb_name = name
    suffix = f'-{suffix}'

    assert zone, '--zone must be specified'
    backend_service_name = f'{lb_name}-backend-service'

    health_check_name = f'{lb_name}-health-checks'
    get_health_check = cli_gcp.compute().healthChecks().get(project=project, healthCheck=health_check_name).execute
    get_health_check = retry(get_health_check, exponent=1.2, allowed_exception_fn=lambda e: e.resp.status == 404)
    health_check = get_health_check()

    group_name = f'{name}-instance-group-manager-{zone}{suffix}'
    cli_gcp.ensure.backend_has_instance_group(verbose, project, zone, backend_service_name, group_name, balancing_mode, cli_gcp.url(health_check))


if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
