#!/usr/bin/env python3
import logging
import shell
import os
import argh
import cli_gcp

def main(name, project=os.environ['GCP_PROJECT'], yes=False):
    if not yes:
        logging.info('going to delete:\n')
        req = cli_gcp.compute().images().get(project=project, image=name).execute()
        logging.info(req['name'])
        logging.info('\nwould you like to proceed? y/n\n')
        assert shell.getch() == 'y', 'abort'
    cli_gcp.compute().images().delete(project=project, image=name).execute()

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
