#!/usr/bin/env python3
import shell
import time
import logging
import os
import argh
import cli_gcp

def main(*selectors,
         end_state='running',
         region=os.environ['GCP_REGION'],
         project=os.environ['GCP_PROJECT']):
    assert end_state in ['running']
    zones = shell.run('gcp-zones --region', region).splitlines()
    ready = False
    start = time.time()
    while not ready:
        ready = True
        for zone in zones:
            for instance in cli_gcp.ls(project, zone, selectors, 'all'):
                if instance['status'].lower() != end_state:
                    logging.info(f'waiting for: {instance["name"]} {instance["status"]}')
                    ready = False
        time.sleep(5)
        assert time.time() - start < 60 * 5

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
