#!/usr/bin/env python3
import sys
import logging
import shell
import os
import argh
import cli_gcp

def main(*selectors,
         region=os.environ['GCP_REGION'],
         project=os.environ['GCP_PROJECT'],
         yes=False):
    zones = shell.run('gcp-zones --region', region, echo=False).splitlines()
    instances = []
    for zone in zones:
        for instance in cli_gcp.ls(project, zone, selectors, 'running'):
            instances += [(zone, instance['name'])]
            print(cli_gcp.format(instance))
    if not yes:
        logging.info('\nwould you like to proceed? y/n\n')
        assert shell.getch() == 'y', 'abort'
    failures = []
    for zone, name in instances:
        try:
            cli_gcp.compute().instances().stop(project=project, zone=zone, instance=name).execute()
        except:
            logging.info(f'failed to stop: {name}')
        logging.info(f'stopped: {name}')
    if failures:
        sys.exit(1)

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
