#!/usr/bin/env python3
import json
import argh
import cli_gcp
import googleapiclient.discovery

def main():
    compute = googleapiclient.discovery.build('compute', 'v1')
    for item in compute.zones().list(project='specto-dev').execute()['items']:
        print(item['name'])

if __name__ == '__main__':
    with cli_gcp.setup():
        argh.dispatch_command(main)
